# MPLAB IDE generated this makefile for use with GNU make.
# Project: 46940086_Garcia_TP.mcp
# Date: Sat Nov 01 16:11:14 2025

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

46940086_Garcia_TP.cof : 46940086_Garcia_TP.o
	$(LD) /p16F84A "46940086_Garcia_TP.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"46940086_Garcia_TP.cof" /M"46940086_Garcia_TP.map" /W /x

46940086_Garcia_TP.o : 46940086_Garcia_TP.asm C:/Program\ Files\ (x86)/Microchip/MPASM\ Suite/p16f84a.inc
	$(AS) /q /p16F84A "46940086_Garcia_TP.asm" /l"46940086_Garcia_TP.lst" /e"46940086_Garcia_TP.err" /d__DEBUG=1

clean : 
	$(RM) "46940086_Garcia_TP.o" "46940086_Garcia_TP.hex" "46940086_Garcia_TP.err" "46940086_Garcia_TP.lst" "46940086_Garcia_TP.cof"

