-- MySQL Script generated by MySQL Workbench
-- Fri Sep 11 03:48:05 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 01_trabajo_integrador_bd1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 01_trabajo_integrador_bd1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `01_trabajo_integrador_bd1` DEFAULT CHARACTER SET utf8 ;
USE `01_trabajo_integrador_bd1` ;

-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`tarea` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`modelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`linea_de_montaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`linea_de_montaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capacidad_productiva` FLOAT NOT NULL,
  `modelo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Lineas_de_montaje_Modelos1_idx` (`modelo_id` ASC) VISIBLE,
  UNIQUE INDEX `Modelos_id_UNIQUE` (`modelo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Lineas_de_montaje_Modelos1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`estacion_de_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`estacion_de_trabajo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `secuencia` INT NOT NULL,
  `tarea_id` INT NOT NULL,
  `linea_de_montaje_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estaciones_de_trabajo_Tareas1_idx` (`tarea_id` ASC) VISIBLE,
  INDEX `fk_estacion_de_trabajo_linea_de_montaje1_idx` (`linea_de_montaje_id` ASC) VISIBLE,
  CONSTRAINT `fk_Estaciones_de_trabajo_Tareas1`
    FOREIGN KEY (`tarea_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`tarea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_de_trabajo_linea_de_montaje1`
    FOREIGN KEY (`linea_de_montaje_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`linea_de_montaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`concecionaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`concecionaria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME NOT NULL,
  `fecha_entrega_esperada` DATETIME NOT NULL,
  `concecionaria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ventas_Concecionaria1_idx` (`concecionaria_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Concecionaria1`
    FOREIGN KEY (`concecionaria_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`concecionaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `venta_id` INT NOT NULL,
  `modelo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_venta_Ventas1_idx` (`venta_id` ASC) VISIBLE,
  INDEX `fk_detalle_venta_modelo1_idx` (`modelo_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_venta_Ventas1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_modelo1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`vehiculo` (
  `numero_chasis` INT NOT NULL AUTO_INCREMENT,
  `modelo_id` INT NOT NULL,
  `detalle_venta_id` INT NULL,
  PRIMARY KEY (`numero_chasis`),
  INDEX `fk_Vehiculo_Modelos1_idx` (`modelo_id` ASC) VISIBLE,
  INDEX `fk_Vehiculo_detalle_venta1_idx` (`detalle_venta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Vehiculo_Modelos1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_detalle_venta1`
    FOREIGN KEY (`detalle_venta_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`detalle_venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME NOT NULL,
  `fecha_entrega_estimada` DATETIME NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pedidos_Proveedores1_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Proveedores1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`insumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TINYTEXT NOT NULL,
  `cantidad_disponible` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`vehiculo_pasa_por_estacion_de_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`vehiculo_pasa_por_estacion_de_trabajo` (
  `vehiculo_numero_chasis` INT NOT NULL,
  `estacion_de_trabajo_id` INT NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `fecha_egreso` DATETIME NULL,
  PRIMARY KEY (`vehiculo_numero_chasis`, `estacion_de_trabajo_id`),
  INDEX `fk_Vehiculo_has_Estaciones_de_trabajo_Estaciones_de_trabajo_idx` (`estacion_de_trabajo_id` ASC) VISIBLE,
  INDEX `fk_Vehiculo_has_Estaciones_de_trabajo_Vehiculo1_idx` (`vehiculo_numero_chasis` ASC) VISIBLE,
  CONSTRAINT `fk_Vehiculo_has_Estaciones_de_trabajo_Vehiculo1`
    FOREIGN KEY (`vehiculo_numero_chasis`)
    REFERENCES `01_trabajo_integrador_bd1`.`vehiculo` (`numero_chasis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_has_Estaciones_de_trabajo_Estaciones_de_trabajo1`
    FOREIGN KEY (`estacion_de_trabajo_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`estacion_de_trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`detalle_pedido` (
  `pedido_id` INT NOT NULL,
  `insumo_id` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  `precio_unitario` FLOAT NOT NULL,
  PRIMARY KEY (`pedido_id`, `insumo_id`),
  INDEX `fk_Pedidos_has_Insumos_Insumos1_idx` (`insumo_id` ASC) VISIBLE,
  INDEX `fk_Pedidos_has_Insumos_Pedidos1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_has_Insumos_Pedidos1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_has_Insumos_Insumos1`
    FOREIGN KEY (`insumo_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`receta_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`receta_modelo` (
  `tarea_id` INT NOT NULL,
  `modelo_id` INT NOT NULL,
  `insumo_id` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  PRIMARY KEY (`tarea_id`, `modelo_id`, `insumo_id`),
  INDEX `fk_Modelos_has_Insumos_Insumos1_idx` (`insumo_id` ASC) VISIBLE,
  INDEX `fk_Modelos_has_Insumos_Modelos1_idx` (`modelo_id` ASC) VISIBLE,
  INDEX `fk_Receta_modelo_Tareas1_idx` (`tarea_id` ASC) VISIBLE,
  CONSTRAINT `fk_Modelos_has_Insumos_Modelos1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modelos_has_Insumos_Insumos1`
    FOREIGN KEY (`insumo_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receta_modelo_Tareas1`
    FOREIGN KEY (`tarea_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`tarea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_trabajo_integrador_bd1`.`precio_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `01_trabajo_integrador_bd1`.`precio_proveedor` (
  `insumo_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  `precio_unitario` FLOAT NOT NULL,
  INDEX `fk_precio_proveedor_Insumos1_idx` (`insumo_id` ASC) VISIBLE,
  INDEX `fk_precio_proveedor_Proveedores1_idx` (`proveedor_id` ASC) VISIBLE,
  PRIMARY KEY (`insumo_id`, `proveedor_id`),
  CONSTRAINT `fk_precio_proveedor_Insumos1`
    FOREIGN KEY (`insumo_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_precio_proveedor_Proveedores1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `01_trabajo_integrador_bd1`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
